name: CI/CD Deploy

on:
  push:
    branches:
      - master  # Ensure this matches your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this secret exists

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /var/www/personal/devarif.co
          git pull origin master
          # Run any additional build steps like composer install or npm install if needed
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
        EOF
